namespace Sathus.Upload.Application.DTOs;

public sealed record UploadSessionResponse(
    Guid Id,
    string SessionId,
    string FileName,
    string FileExtension,
    string MimeType,
    long SizeBytes,
    string? StorageKey,
    string? Checksum,
    long ChunkSize,
    int TotalChunks,
    int UploadedChunks,
    double Progress,
    string Status,
    string? ErrorMessage,
    DateTime StartedAt,
    DateTime? CompletedAt,
    Guid? CreatedBy,
    Guid? TenantId,
    Guid? FolderId,
    Guid? ParentSessionId,
    bool IsFolder,
    string? FolderPath,
    DateTime CreatedAt,
    DateTime UpdatedAt)
{
    public static UploadSessionResponse From(UploadSession session) => new(
        session.Id,
        session.SessionId,
        session.FileName.Value,
        session.FileExtension.Value,
        session.MimeType.Value,
        session.FileSize.Bytes,
        session.StorageKey?.Value,
        session.Checksum?.Value,
        session.ChunkSize,
        session.TotalChunks,
        session.UploadedChunks,
        session.Progress,
        session.Status.ToString(),
        session.ErrorMessage,
        session.StartedAt,
        session.CompletedAt,
        session.CreatedBy,
        session.TenantId,
        session.FolderId,
        session.ParentSessionId,
        session.IsFolder,
        session.FolderPath,
        session.CreatedAt,
        session.UpdatedAt);
}
