'use client';

import React, { useState, useMemo } from 'react';
import { Cpu, HardDrive, Sliders, Copy, Check, AlertTriangle, ShieldCheck } from 'lucide-react';

export function SparkMemoryCalculator() {
  const [dataSizeGb, setDataSizeGb] = useState<number>(250);
  const [workerRamGb, setWorkerRamGb] = useState<number>(32);
  const [coresPerNode, setCoresPerNode] = useState<number>(8);
  const [workloadType, setWorkloadType] = useState<'pyspark-arrow' | 'shuffle-heavy' | 'standard-etl'>('pyspark-arrow');
  const [copied, setCopied] = useState<boolean>(false);

  // Calculation logic
  const calc = useMemo(() => {
    // 1. Determine optimal cores per executor: sweet spot is 4-5 cores to balance task parallelism with JVM GC
    const executorCores = coresPerNode >= 8 ? 4 : Math.max(2, Math.floor(coresPerNode / 2));
    const executorsPerNode = Math.max(1, Math.floor(coresPerNode / executorCores));

    // 2. Available RAM per executor container
    // Reserve ~10-15% of node RAM for OS and cluster daemon processes
    const usableNodeRam = workerRamGb * 0.88;
    const rawContainerRamGb = usableNodeRam / executorsPerNode;

    // 3. Off-heap memory overhead sizing
    // PySpark with PyArrow/Pandas UDFs needs 20-25% off-heap memory
    let overheadFraction = 0.15;
    if (workloadType === 'pyspark-arrow') overheadFraction = 0.25;
    if (workloadType === 'shuffle-heavy') overheadFraction = 0.20;

    const overheadRamGb = Math.max(0.384, Math.round(rawContainerRamGb * overheadFraction * 10) / 10);
    const executorMemoryGb = Math.floor(rawContainerRamGb - overheadRamGb);

    // 4. Partition sizing: Target 128MB per partition
    const targetPartitionSizeMb = 128;
    const dataSizeMb = dataSizeGb * 1024;
    const calculatedPartitions = Math.max(200, Math.ceil(dataSizeMb / targetPartitionSizeMb));

    // 5. Unified memory split (60% unified, 40% user memory)
    const unifiedMemoryGb = Math.round(executorMemoryGb * 0.6 * 10) / 10;
    const executionStorageSplitGb = Math.round((unifiedMemoryGb / 2) * 10) / 10;

    const sparkConfig = `# Generated by Sathus Distributed Systems Calculator
spark.executor.instances: 16
spark.executor.cores: ${executorCores}
spark.executor.memory: ${executorMemoryGb}g
spark.executor.memoryOverhead: ${Math.ceil(overheadRamGb * 1024)}m
spark.sql.shuffle.partitions: ${calculatedPartitions}
spark.sql.adaptive.enabled: true
spark.sql.adaptive.skewJoin.enabled: true
spark.sql.adaptive.coalescePartitions.enabled: true
spark.memory.fraction: 0.60
spark.memory.storageFraction: 0.50`;

    return {
      executorCores,
      executorsPerNode,
      executorMemoryGb,
      overheadRamGb,
      calculatedPartitions,
      unifiedMemoryGb,
      executionStorageSplitGb,
      sparkConfig,
    };
  }, [dataSizeGb, workerRamGb, coresPerNode, workloadType]);

  const copyConfig = () => {
    navigator.clipboard.writeText(calc.sparkConfig);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-2xl border-2 border-primary/30 bg-card/95 p-6 md:p-8 space-y-6 shadow-2xl backdrop-blur-md">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-border/60 pb-4">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary uppercase tracking-wider mb-2">
            <Cpu className="h-3.5 w-3.5" />
            Interactive Engineering Asset
          </div>
          <h3 className="text-xl md:text-2xl font-bold text-foreground">
            Spark Executor Memory &amp; Partition Sizing Calculator
          </h3>
          <p className="text-xs md:text-sm text-muted-foreground mt-1">
            Compute container allocation, off-heap buffers, and AQE partition targets based on Sathus distributed systems sizing formulas.
          </p>
        </div>
        <div className="flex items-center gap-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20 px-3 py-2 text-xs font-semibold text-emerald-400">
          <ShieldCheck className="h-4 w-4 shrink-0" />
          <span>OOM Protection Formula Active</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Controls Column */}
        <div className="space-y-5">
          {/* Input 1: Data Size */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs font-semibold text-foreground">
              <span>Stage Input Data Size:</span>
              <span className="font-mono text-primary font-bold">{dataSizeGb} GB</span>
            </div>
            <input
              type="range"
              min="10"
              max="2000"
              step="10"
              value={dataSizeGb}
              onChange={(e) => setDataSizeGb(Number(e.target.value))}
              className="w-full h-2 bg-muted rounded-lg appearance-none cursor-pointer accent-primary"
            />
            <div className="flex justify-between text-[10px] text-muted-foreground font-mono">
              <span>10 GB</span>
              <span>500 GB</span>
              <span>1,000 GB</span>
              <span>2,000 GB</span>
            </div>
          </div>

          {/* Input 2: Worker Node RAM */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs font-semibold text-foreground">
              <span>Worker Node Physical RAM:</span>
              <span className="font-mono text-primary font-bold">{workerRamGb} GB</span>
            </div>
            <div className="grid grid-cols-4 gap-2">
              {[16, 32, 64, 128].map((ram) => (
                <button
                  key={ram}
                  type="button"
                  onClick={() => setWorkerRamGb(ram)}
                  className={`py-1.5 text-xs font-mono font-bold rounded-lg border transition-all ${
                    workerRamGb === ram
                      ? 'border-primary bg-primary/20 text-primary shadow-sm'
                      : 'border-border/60 bg-muted/30 text-muted-foreground hover:bg-muted/60'
                  }`}
                >
                  {ram} GB
                </button>
              ))}
            </div>
          </div>

          {/* Input 3: Cores Per Node */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs font-semibold text-foreground">
              <span>Cores per Worker Node:</span>
              <span className="font-mono text-primary font-bold">{coresPerNode} Cores</span>
            </div>
            <div className="grid grid-cols-4 gap-2">
              {[4, 8, 16, 32].map((cores) => (
                <button
                  key={cores}
                  type="button"
                  onClick={() => setCoresPerNode(cores)}
                  className={`py-1.5 text-xs font-mono font-bold rounded-lg border transition-all ${
                    coresPerNode === cores
                      ? 'border-primary bg-primary/20 text-primary shadow-sm'
                      : 'border-border/60 bg-muted/30 text-muted-foreground hover:bg-muted/60'
                  }`}
                >
                  {cores} Cores
                </button>
              ))}
            </div>
          </div>

          {/* Input 4: Workload Profile */}
          <div className="space-y-2">
            <span className="text-xs font-semibold text-foreground">Workload Execution Profile:</span>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => setWorkloadType('pyspark-arrow')}
                className={`p-2.5 text-left rounded-lg border text-xs transition-all ${
                  workloadType === 'pyspark-arrow'
                    ? 'border-primary bg-primary/20 text-foreground font-semibold'
                    : 'border-border/60 bg-muted/20 text-muted-foreground hover:bg-muted/40'
                }`}
              >
                <div className="font-bold">PySpark / PyArrow</div>
                <div className="text-[10px] text-muted-foreground mt-0.5">25% Off-heap overhead</div>
              </button>
              <button
                type="button"
                onClick={() => setWorkloadType('shuffle-heavy')}
                className={`p-2.5 text-left rounded-lg border text-xs transition-all ${
                  workloadType === 'shuffle-heavy'
                    ? 'border-primary bg-primary/20 text-foreground font-semibold'
                    : 'border-border/60 bg-muted/20 text-muted-foreground hover:bg-muted/40'
                }`}
              >
                <div className="font-bold">Shuffle Heavy</div>
                <div className="text-[10px] text-muted-foreground mt-0.5">Heavy SortMergeJoins</div>
              </button>
              <button
                type="button"
                onClick={() => setWorkloadType('standard-etl')}
                className={`p-2.5 text-left rounded-lg border text-xs transition-all ${
                  workloadType === 'standard-etl'
                    ? 'border-primary bg-primary/20 text-foreground font-semibold'
                    : 'border-border/60 bg-muted/20 text-muted-foreground hover:bg-muted/40'
                }`}
              >
                <div className="font-bold">Standard SQL / ETL</div>
                <div className="text-[10px] text-muted-foreground mt-0.5">15% Standard overhead</div>
              </button>
            </div>
          </div>
        </div>

        {/* Results Column */}
        <div className="space-y-4 rounded-xl border border-border/80 bg-neutral-950 p-5 font-mono text-xs">
          <div className="flex items-center justify-between border-b border-border/40 pb-3">
            <span className="text-primary font-bold uppercase tracking-wider text-[11px]">
              Tuned Spark Submit Sizing
            </span>
            <button
              onClick={copyConfig}
              className="inline-flex items-center gap-1.5 rounded bg-muted/60 px-2.5 py-1 text-[11px] font-semibold text-foreground hover:bg-primary/20 hover:text-primary transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? 'Copied!' : 'Copy Config'}
            </button>
          </div>

          <div className="grid grid-cols-2 gap-3 pt-1">
            <div className="rounded-lg bg-neutral-900 p-3 border border-border/40">
              <div className="text-[10px] text-muted-foreground uppercase">spark.executor.memory</div>
              <div className="text-lg font-bold text-emerald-400">{calc.executorMemoryGb} GB</div>
              <div className="text-[10px] text-muted-foreground mt-1">JVM Heap per container</div>
            </div>
            <div className="rounded-lg bg-neutral-900 p-3 border border-border/40">
              <div className="text-[10px] text-muted-foreground uppercase">spark.executor.memoryOverhead</div>
              <div className="text-lg font-bold text-amber-400">{Math.ceil(calc.overheadRamGb * 1024)} MB</div>
              <div className="text-[10px] text-muted-foreground mt-1">Off-heap Python/NIO safety buffer</div>
            </div>
            <div className="rounded-lg bg-neutral-900 p-3 border border-border/40">
              <div className="text-[10px] text-muted-foreground uppercase">spark.executor.cores</div>
              <div className="text-lg font-bold text-cyan-400">{calc.executorCores} Cores</div>
              <div className="text-[10px] text-muted-foreground mt-1">Optimal GC pause limit</div>
            </div>
            <div className="rounded-lg bg-neutral-900 p-3 border border-border/40">
              <div className="text-[10px] text-muted-foreground uppercase">spark.sql.shuffle.partitions</div>
              <div className="text-lg font-bold text-purple-400">{calc.calculatedPartitions}</div>
              <div className="text-[10px] text-muted-foreground mt-1">~128MB per target partition</div>
            </div>
          </div>

          <div className="rounded-lg bg-neutral-900/80 p-3 border border-border/40 space-y-2">
            <div className="text-[10px] uppercase font-bold text-muted-foreground">JVM Unified Memory Allocation</div>
            <div className="flex items-center gap-2 h-4 w-full rounded bg-muted/40 overflow-hidden text-[9px] font-bold text-center">
              <div style={{ width: '30%' }} className="bg-blue-600/80 text-white h-full flex items-center justify-center">
                Exec ({calc.executionStorageSplitGb}G)
              </div>
              <div style={{ width: '30%' }} className="bg-emerald-600/80 text-white h-full flex items-center justify-center">
                Storage ({calc.executionStorageSplitGb}G)
              </div>
              <div style={{ width: '40%' }} className="bg-neutral-700 text-neutral-300 h-full flex items-center justify-center">
                User (40%)
              </div>
            </div>
          </div>

          <pre className="rounded-lg bg-black/60 p-3 text-[11px] text-neutral-200 overflow-x-auto leading-relaxed border border-border/30">
            <code>{calc.sparkConfig}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
