global using Sathus.SharedKernel;
global using Sathus.SharedKernel.Entities;
global using Sathus.SharedKernel.Events;
global using Sathus.SharedKernel.Exceptions;
global using Sathus.Navigation.Domain.Entities;
global using Sathus.Navigation.Domain.Enums;
global using Sathus.Navigation.Domain.ValueObjects;
global using Sathus.Navigation.Domain.Events;
global using Sathus.Navigation.Domain.Exceptions;
